name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Create Release Job"
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: "Check-out Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate the changelog for the release
      - name: "Generate Release Changelog"
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true"
          stripHeaders: "true"
          stripGeneratorNotice: "true"

      # Extract the version name from the tag
      - name: "Extract Version Name"
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      # Create the GitHub release
      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "${{ steps.get-version.outputs.VERSION }}"
          body: "${{ steps.generate-release-changelog.outputs.changelog }}"
          prerelease: ${{ startsWith(steps.get-version.outputs.VERSION, 'v0.') }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: True
